name: Build MathDoc

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Get source code
        uses: actions/checkout@v5

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            g++ \
            qt6-base-dev

      - name: Install CMake
        if: runner.os != 'Linux'
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmakeGenerator: Ninja

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.3'
          modules: ''
          cache: true

      - name: Configure
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build --config Release --verbose --parallel
